---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse
  - src: git@github.com/khayrullinii/lighthouse-role
    scm: git
    version: "v.1.0.0"
    name: lighthouse
  - src: git@github.com/khayrullinii/vector-role
    scm: git
    version: "v1.0.0"
    name: vector