{
 "title": "Netology",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "FREE MEM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vda2\",fstype=\"ext4\",instance=\"158.160.109.98:9100\",job=\"nodeexporter\",mountpoint=\"/\"}",
     "legendFormat": "free mem vda2"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU IDLE"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"158.160.109.98:9100\",job=\"nodeexporter\"}",
     "legendFormat": "RAM free"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"158.160.109.98:9100\",job=\"nodeexporter\"}",
     "legendFormat": "CpuLA-1"
    },
    {
     "expr": "node_load5{instance=\"158.160.109.98:9100\",job=\"nodeexporter\"}",
     "legendFormat": "CpuLA-5"
    },
    {
     "expr": "node_load15{instance=\"158.160.109.98:9100\",job=\"nodeexporter\"}",
     "legendFormat": "CpuLA-15"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } }
 ]
}